# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-27 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailsearch.index


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # noqa: E501
                ('name_en', models.CharField(max_length=1000)),
                ('name_be', models.CharField(max_length=1000)),
                ('name_ru', models.CharField(max_length=1000)),
                ('address_en', models.CharField(max_length=1000)),
                ('address_be', models.CharField(max_length=1000)),
                ('address_ru', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.wagtailsearch.index.Indexed, models.Model),
        ),
    ]
