language: python
sudo: false
dist: trusty
python:
  - "2.7"
addons:
  postgresql: "9.6"
services:
  - postgresql
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get install docker-engine
install:
  - pip install tox==2.3.2
before_script:
  - psql -c 'create database filmfest;' -U postgres
script:
  - tox -e "py27-{sqlite,pg}"
deploy:
  - provider: script
    script: ./scripts/push_image.sh
    on:
      branch: deploy
  - provider: script
    script: ./scripts/deploy.sh
    on:
      branch: deploy
