language: python
sudo: false
python:
  - "2.7"
addons:
  postgresql: "9.4"
services:
  - postgresql
install: "pip install tox"
before_script:
  - psql -c 'create database filmfest;' -U postgres
script: tox -e "py27-{sqlite,pg}"
