FROM nginx

RUN echo '\n\
    server {\n\
        listen       80;\n\
        server_name www.next.filmfest.by;\n\
        rewrite ^ http://next.filmfest.by/ permanent;\n\
    }\n\
    \n\
    server {\n\
        listen       80;\n\
        server_name  next.filmfest.by;\n\
        \n\
        charset utf-8;\n\
        \n\
        location / {\n\
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n\
            proxy_set_header Host $http_host;\n\
            proxy_redirect off;\n\
            \n\
            proxy_pass   http://web:8000;\n\
        }\n\
        location /static/ {\n\
                 access_log off;\n\
                 expires 2d;\n\
                 alias   /app/static/;\n\
        }\n\
        location /media/ {\n\
                 access_log off;\n\
                 expires 2d;\n\
                 alias   /app/media/;\n\
        }\n\
        location /robots.txt {\n\
                 access_log off;\n\
                 expires 2d;\n\
                 alias   /app/static/robots.txt;\n\
        }\n\
    }\n\
' > /etc/nginx/conf.d/filmfest.conf