# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-28 22:00
from __future__ import unicode_literals

from django.db import migrations
from django.utils import timezone

from cpm_generic.migration_utils import (add_subpage, remove_subpage,
                                         get_content_type)



def _add_news_page(apps, schema_editor):
    NewsIndexPage = apps.get_model('news.NewsIndexPage')
    NewsPage = apps.get_model('news.NewsPage')

    news_page_ct = get_content_type(apps, 'news', 'newspage')

    newsindex = NewsIndexPage.objects.get(slug='news')
    add_subpage(
        newsindex,
        NewsPage,
        content_type=news_page_ct,
        title=u'News entry #1',
        seo_title=u'News entry #1',
        slug='news_entry_1',
        search_description=u'Search Description for news entry',
        date=timezone.now()
    )
    add_subpage(
        newsindex,
        NewsPage,
        content_type=news_page_ct,
        title=u'News entry #2',
        seo_title=u'News entry #2',
        slug='news_entry_2',
        search_description=u'Search Description for news entry',
        date=timezone.now()
    )


# TODO: make working correct: clean up is not correct
def remove_news_page(apps, schema_editor):
    NewsIndexPage = apps.get_model('news.NewsIndexPage')

    news_page_ct = get_content_type(apps, 'news', 'newspage')

    newsindexpage = NewsIndexPage.objects.get(slug='news')

    remove_subpage(
        newsindexpage,
        NewsIndexPage,
        content_type=news_page_ct,
        slug='news_entry_1',
    )
    remove_subpage(
        newsindexpage,
        NewsIndexPage,
        content_type=news_page_ct,
        slug='news_entry_2',
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0002_index'),
    ]

    operations = [
        migrations.RunPython(_add_news_page, remove_news_page),
    ]
