# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-06 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('cpm_data', '0011_add_jury_data_to_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPageRelatedPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartnersPage',
            fields=[
                ('page_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='wagtailcore.Page')),
                ('entry_en', wagtail.wagtailcore.fields.RichTextField(default='')),
                ('entry_be', wagtail.wagtailcore.fields.RichTextField(default='')),
                ('entry_ru', wagtail.wagtailcore.fields.RichTextField(default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='partnerpagerelatedpartner',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_partners', to='partners.PartnersPage'),
        ),
        migrations.AddField(
            model_name='partnerpagerelatedpartner',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cpm_data.Partner'),
        ),
    ]
