# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-06 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerspage',
            name='name_be',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerspage',
            name='name_en',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerspage',
            name='name_ru',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
