# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # noqa
                ('name_en', models.CharField(max_length=250)),
                ('name_be', models.CharField(max_length=250)),
                ('name_ru', models.CharField(max_length=250)),
            ],
        ),
    ]
