# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-27 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cpm_data', '0002_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonRelatedJuryMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # noqa
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),  # noqa
                ('category_en', models.CharField(blank=True, default='', max_length=250)),  # noqa
                ('category_be', models.CharField(blank=True, default='', max_length=250)),  # noqa
                ('category_ru', models.CharField(blank=True, default='', max_length=250)),  # noqa
                ('jury_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cpm_data.JuryMember')),  # noqa
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_jury_members', to='cpm_data.Season')),  # noqa
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeasonRelatedPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # noqa
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),  # noqa
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_partners', to='cpm_data.Season')),  # noqa
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cpm_data.Partner')),  # noqa
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
