# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-27 22:21
from __future__ import unicode_literals

import json
import os

from django.core.files import File
from django.db import migrations

from cpm_generic.migration_utils import get_image_model


DIR_0005 = os.path.join(os.path.dirname(__file__), '0005')


def _get_data():
    with open(os.path.join(DIR_0005, 'data.json')) as data_file:
        return json.load(data_file)


def _get_photo_path(filename):
    return os.path.join(DIR_0005, 'photo', filename)


def add_jurymembers(apps, schema_editor):
    JuryMember = apps.get_model('cpm_data.JuryMember')
    Image = get_image_model(apps)
    Collection = apps.get_model('wagtailcore.Collection')

    collection_id = Collection.objects.filter(depth=1)[0]

    for item in _get_data():
        photo = Image(title=item['name_en'], collection=collection_id)
        with open(_get_photo_path(item['photo']), 'rb') as photo_file:
            photo.file.save(name=item['photo'], content=File(photo_file))
            photo.save()

        JuryMember(
            name_en=item['name_en'],
            name_be=item['name_be'],
            name_ru=item['name_ru'],
            info_en=item['info_en'],
            info_be=item['info_be'],
            info_ru=item['info_ru'],
            country=item['country'],
            photo=photo
        ).save()


def remove_jurymembers(apps, schema_editor):
    JuryMember = apps.get_model('cpm_data.JuryMember')

    names = [item['name_en'] for item in _get_data() if item['name_en']]
    JuryMember.objects.filter(name_en__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cpm_data', '0004_add_seasons_data'),
    ]

    operations = [
        migrations.RunPython(add_jurymembers, remove_jurymembers),
    ]
