# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-27 22:21
from __future__ import unicode_literals

import json
from operator import itemgetter
import os

from django.core.files import File
from django.db import migrations

from cpm_generic.migration_utils import get_image_model


DIR_0007 = os.path.join(os.path.dirname(__file__), '0007')


def _get_data():
    with open(os.path.join(DIR_0007, 'data.json')) as data_file:
        return json.load(data_file)


def _get_photo_path(filename):
    return os.path.join(DIR_0007, 'photo', filename)


def _get_season(apps):
    Season = apps.get_model('cpm_data.Season')
    return Season.objects.get(name_en='2014')


def add_jurymembers(apps, schema_editor):
    JuryMember = apps.get_model('cpm_data.JuryMember')
    SeasonJuryMember = apps.get_model('cpm_data.SeasonRelatedJuryMember')
    Image = get_image_model(apps)
    Collection = apps.get_model('wagtailcore.Collection')

    collection_id = Collection.objects.filter(depth=1)[0]
    season = _get_season(apps)

    for item in sorted(_get_data(), key=itemgetter('name_en'), reverse=True):

        photo = Image(title=item['name_en'], collection=collection_id)
        with open(_get_photo_path(item['photo']), 'rb') as photo_file:
            photo.file.save(name=item['photo'], content=File(photo_file))
            photo.save()

        jury_member = JuryMember(
            name_en=item['name_en'],
            name_be=item['name_be'],
            name_ru=item['name_ru'],
            info_en=item['info_en'],
            info_be=item['info_be'],
            info_ru=item['info_ru'],
            country=item['country'],
            photo=photo
        )
        jury_member.save()

        SeasonJuryMember(season=season, jury_member=jury_member).save()


def remove_jurymembers(apps, schema_editor):
    JuryMember = apps.get_model('cpm_data.JuryMember')
    SeasonJuryMember = apps.get_model('cpm_data.SeasonRelatedJuryMember')

    season = _get_season(apps)
    names = [item['name_en'] for item in _get_data() if item['name_en']]
    jury_members = JuryMember.objects.filter(name_en__in=names)

    SeasonJuryMember.objects.filter(
        season=season,
        jury_member__in=jury_members
    ).delete()
    jury_members.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cpm_data', '0006_rename_fk_page_to_season'),
    ]

    operations = [
        migrations.RunPython(add_jurymembers, remove_jurymembers),
    ]
