# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-19 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm_data', '0009_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurymember',
            name='info_be',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='jurymember',
            name='info_en',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='jurymember',
            name='info_ru',
            field=models.CharField(max_length=5000),
        ),
    ]
