# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-10 22:48
from __future__ import unicode_literals

from functools import partial
import json
import os

from django.core.files import File
from django.db import migrations

from cpm_generic.migration_utils import get_image_model


DIR_0011 = os.path.join(os.path.dirname(__file__), '0011')


def _get_photo_path(filename):
    return os.path.join(DIR_0011, filename)


def _get_season(apps, season_name):
    Season = apps.get_model('cpm_data.Season')
    return Season.objects.get(name_en=season_name)


def _get_data(season_year):
    with open(os.path.join(
            DIR_0011,
            'jury_' + season_year + '.json'
    )) as data_file:
        return json.load(data_file)


def add_jurymembers(apps, schema_editor, season_name):
    season = _get_season(apps, season_name=season_name)
    JuryMember = apps.get_model('cpm_data.JuryMember')
    Image = get_image_model(apps)
    Collection = apps.get_model('wagtailcore.Collection')

    collection_id = Collection.objects.filter(depth=1)[0]

    for item in _get_data(season_name):
        photo = Image(title=item['name_en'], collection=collection_id)

        with open(_get_photo_path(item['photo']), 'rb') as photo_file:
            photo.file.save(name=item['photo'], content=File(photo_file))
            photo.save()

        jurymember, _created = JuryMember.objects.get_or_create(
            name_en=item['name_en'],
            name_be=item['name_be'],
            name_ru=item['name_ru'],
            info_en=item['info_en'],
            info_be=item['info_be'],
            info_ru=item['info_ru'],
            country=item['country'],
            photo=photo,
        )

        SeasonJuryMember = apps.get_model('cpm_data.SeasonRelatedJuryMember')

        SeasonJuryMember(
            jury_member=jurymember,
            season=season,
            category_en='',
            category_be='',
            category_ru='',
        ).save()


def remove_jurymembers(apps, schema_editor, season_name):
    JuryMember = apps.get_model('cpm_data.JuryMember')

    names = [item['name_en'] for item in _get_data('2015') if item['name_en']]
    jury_members = JuryMember.objects.filter(name_en__in=names)
    JuryMember.objects.filter(name_en__in=names).delete()

    SeasonJuryMember = apps.get_model('cpm_data.SeasonRelatedJuryMember')
    season = _get_season(apps, season_name)
    SeasonJuryMember.objects.filter(
        season=season,
        jury_member__in=jury_members
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cpm_data', '0010_auto_change_limits_for_jury_fields'),
    ]

    operations = [
        migrations.RunPython(
            partial(add_jurymembers, season_name=season_name),
            partial(remove_jurymembers, season_name=season_name)
        ) for season_name in ['2015', '2016']
    ]

    # operations = [
    #     migrations.RunPython(
    #         partial(add_partners, season_name=season_name),
    #         partial(remove_partners, season_name=season_name)
    #     ) for season_name in ['2012', '2013', '2015']
    # ]
